### ISSUE TITLE
error for ExternalAzureAD/guest users

### ISSUE THREAD

**Issue by vidarak** [dotraphael/RFL.Microsoft.Intune#2]
The script throws an error when it encounters an ExternalAzureAD guest user.
Example:
An error occurred GET https://graph.microsoft.com/v1.0/users/user.name_external.tld

**Comment by dotraphael** [comment]
Hi @vidarak,

Can you send me an export of the error ($Error | select * | Export-Clixml c:\temp\error.xml) and the the log file? it should be in the %temp% and it is called ExportIntuneData.log

**Comment by vidarak** [comment]
Given what you are asking for I think I should stop using this script.

**Comment by dotraphael** [comment]
Hi @vidarak<

sad that you think asking for more info about the error and the log of the application is asking too much...

**Comment by vidarak** [comment]
What you ask for contains client secret and bearerer tokens etc. 
You asking for files containing such information without warning makes me feel uneasy about this. I appreciate the effort and quick response though.

**Comment by dotraphael** [comment]
Hi @vidarak

any information that you feel shouldn't be shared, can be removed from the logs
